services:
  Portainer:
    image: 6053537/portainer-ce:latest
    container_name: portainer
    ports:
      - 0:9000
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./_/data:/data
    restart: unless-stopped
    networks:
      - software-network
  portainer_agent:
    image: portainer/agent
    ports:
      - 0:9001
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - //var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - software-network
networks:
  software-network:
    external: true
