services:
  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "0:80"
      - "0:81"
      - "0:443"
    volumes:
      - ./_/data:/data
      - ./_/etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    networks:
      - software-network
networks:
  software-network:
    external: true
