services:
  beszel:
    image: "henrygd/beszel"
    container_name: "beszel"
    ports:
      - "0:8090"
    volumes:
      - ./data:/beszel_dat
    restart: unless-stopped
    networks:
      - software-network
networks:
  software-network:
    external: true
