services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    ports:
      - 0:8080
      - 0:50000
    # volumes:
    restart: unless-stopped
    networks:
      - software-network
networks:
  software-network:
    external: true
